CREATE TABLE [dbo].[Users]
(
  [Id] BIGINT NOT NULL IDENTITY PRIMARY KEY,
  [Email] NVARCHAR(100) MASKED WITH (FUNCTION = 'email()'),
  [InsertedOn] DATETIME NOT NULL DEFAULT(GETUTCDATE()),
  [LastModifiedOn] DATETIME NULL
)