CREATE TABLE [dbo].[CryptoAlerts]
(
  [Id] BIGINT NOT NULL IDENTITY PRIMARY KEY,
  [UserId] BIGINT NOT NULL FOREIGN KEY REFERENCES Users([Id]),
  [Symbol] NVARCHAR(10) NOT NULL,
  [High] DECIMAL (30,10) NOT NULL,
  [Low] DECIMAL (30,10) NOT NULL
)
